kind: pipeline
type: docker
name: CI_Toxi_IARecognition

trigger:
  event:
    - push

steps:
  - name: get-images
    image: python:3.8
    commands:
      - apt-get update
      - apt-get install -y cmake
      - pip install -r requirements.txt
      - python getImagesApi.py

  - name: build
    image: python:3.8
    commands:
      - cd codeIA
      - python3 mainIA.py Images/Remi.jpg
    depends_on: [get-images]

  # - name: test
  #   image: python:3.8
  #   commands:
  #     - npm test
  #   depends_on: [build]

  - name: code-inspection_sonar
    image: sonarsource/sonar-scanner-cli
    secrets: [ Login_Sonar_Toxi_AIRecognition ]
    settings:
      sonar_host: https://codefirst.iut.uca.fr/sonar/
      sonar_token:
        from_secrets: Login_Sonar_Toxi_AIRecognition
    commands:
      - sonar-scanner -X -D sonar.projectKey=toxiAIRecognition -D sonar.host.url=$${sonar_host}
    # depends_on: [test]

# ---

# kind: pipeline
# type: docker
# name: CI_Toxi_IARecognition

# trigger:
#   branch:
#     - master
#   event:
#     - push


# steps:
#   - name: docker-build-and-push
#     image: plugins/docker
#     settings:
#        dockerfile: Dockerfile
#        context: .
#        registry: hub.codefirst.iut.uca.fr
#        repo: hub.codefirst.iut.uca.fr/nathan.verdier/toxic-api
#        username:
#          from_secret: 
#        password:
#          from_secret: 